version: "3"

services:

  springbootapp:
    build: .
    container_name: gestion_usuarios
    
    ports:
      - 8090:8090
    #command: sh -c "dockerize -wait tcp://postgres:8091 -timeout 300s -wait-retry-interval 30s /sayhello"
    #networks:
      #- my-net
    #expose:
      #- 8090
    #restart: always
    #ports:
      #- 8090:8080
    environment:
      #- DB_SERVER=database
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    #links:
      #- database
    #depends_on:
      #- database
   
      #- back-tier     ff
    #depends_on:
    #  - database
  

    
    #volumes:
      #- ./postgres:/var/lib/postgresql/data

    #env_file:
    #  - database.env # configure postgres
    #volumes:
    #  - database-data:/var/lib/postgresql/data/
  
networks:
  front-tier:
  back-tier:

    